### Create a new Card
POST http://localhost:3000/cards
Content-Type: application/json

{
  "title": "Configure Database",
  "description": "Integration of columns and cards",
  "columnId": 1
}

###

### List Columns with Cards (Kanban)
GET http://localhost:3000/columns

###

### Find a Card by ID
GET http://localhost:3000/cards/1

###

### Update a Card (Move to Column 2)
PATCH http://localhost:3000/cards/1
Content-Type: application/json

{
  "columnId": 2
}

###

### Delete a Card
DELETE http://localhost:3000/cards/1